export 'package:getx_demo/views/home.dart';
export 'package:getx_demo/views/styling_screen.dart';
export 'package:getx_demo/views/paging_screen.dart';
export 'package:getx_demo/views/builder_screen.dart';
export 'package:getx_demo/views/paging/page1.dart';
export 'package:getx_demo/views/builders/getbuilder_screen.dart';
export 'package:getx_demo/views/builders/obx_getx_screen.dart';
export 'package:getx_demo/views/language.dart';
export 'package:getx_demo/views/bottom_navigation_screen.dart';
